--- BETWEEN: SELECCIONAR VALORES ENTRE MINIMOS Y MAXIMOS

select * from "esquema"."PEDIDOS" where "IMPORTE" BETWEEN 100 and 200
select * from "esquema"."PEDIDOS" WHERE "PEDIDOS"."FECHA" BETWEEN '2020-08-02' AND '2020-08-04' 

