/* FECJA Y HORA */
-- SELECT now()
-- SELECT TIMEOFDAY() -- INDICA LA FECHA
-- SELECT CURRENT_TIME -- INDICA LA HORA ACTUAL
-- select CURRENT_DATE -- INDICA LA FECHA

SELECT EXTRACT (DAY FROM "FECHA") AS "DIAA"
FROM esquema."PEDIDOS" -- EXTRAE EL DIA